pluginInfo:
  # This is default sample specification
  # Feel free to change it
  # Call flowpdk showdoc pluginspec to see the list of available fields and their description
  pluginName: 'QA-PerlGit'
  version: '1.0.0'
  description: 'Perl plugin for git'
  author: 'Ed Serbin'
  supportUrl: 'https://github.com'
  category: 'Utilities'

# REST-backed plugin configuration
configuration:
  checkConnection: true
  restConfigInfo:
    endpointLabel: 'My REST Endpoint'
    checkConnectionUri: '/user/repos'
    headers:
      Accept: 'application/json'
    authSchemes:
      bearer:
        passwordLabel: 'Bearer token'
        description: 'Token to connect to...'
      basic:
        userNameLabel: 'Username'
        passwordLabel: 'Password'
        description: 'Username and password to connect to ...'
  hasProxySupport: true
  hasDebugLevel: true

procedures:
-
  name: 'Get User Info'
  description:  'Get User Info'
  hasConfig: true
  shell: 'ec-perl'
  # Connects REST endpoint to the plugin procedure
  restProcedureInfo:
    url: '/user/repos'
    methodName: 'getGitUserInfo'
    httpMethod: 'GET'
